ALTER TABLE t_p95371417_alisa_eng_club_app.lessons
  ADD COLUMN IF NOT EXISTS lesson_date DATE,
  ADD COLUMN IF NOT EXISTS group_id INTEGER REFERENCES t_p95371417_alisa_eng_club_app.groups(id),
  ADD COLUMN IF NOT EXISTS recurring BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS weekday SMALLINT,
  ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE
